pipelineAccount:
  awsAccountId: 009507777973
  awsRegion: us-east-1

devAccount:
  awsAccountId: 095929019002
  awsRegion: us-east-1

prodAccount:
  awsAccountId: 981445861826
  awsRegion: us-east-1

dev:
  jobs:
    ProcessLegislators:
      inputLocation: s3://awsglue-datasets/examples/us-legislators/all/persons.json

prod:
  jobs:
    ProcessLegislators:
      inputLocation: s3://awsglue-datasets/examples/us-legislators/all/persons.json